### ISSUE TITLE
不发送消息的情况下，无法将好友或者群加入到会话列表

### ISSUE THREAD

**Issue by FourLeafClover** [wildfirechat/web-chat#10]
场景描述:  在通讯录里面搜索某位好友或者群并发起消息。如果该好友或者群不在历史会话，web端未提供API将该好友或者群加入到会话列表。
期望: 希望提供api，传递用户id或者群id。api判断到如果该id不在历史会话列表里就自动将其添加到会话列表第一个。类似于PC微信的场景。
![image](https://user-images.githubusercontent.com/8449788/83024518-17376680-a061-11ea-99aa-6f14e2320d6e.png)

**Comment by imndx** [comment]
你好。

可以使用这个```wfc.setConversationTimestamp```，这个会更新会话的时间戳，如果会话不存在，则创建新的会话
