### ISSUE TITLE
所有浏览器，pdf文件可以上传，但是无法点击下载

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/web-chat#14]

**Comment by imndx** [comment]
点击之后，是在线预览吗？

**Comment by Charlie191011** [comment]
点击之后没有预览，PDF应该是不支持预览的。
是点文件图标右侧的红色下载按钮，没有反应。

**Comment by Charlie191011** [comment]
chrome浏览器下载时，文件名被统一改成了“true”。所有文件下载时都变成了这个名字。
![微信图片_20200724132009](https://user-images.githubusercontent.com/61824879/88362798-6d4e2f00-cdb0-11ea-9c61-e00bab133f92.png)
