### ISSUE TITLE
Safari12版本，无法登录会报跨域错误，但是13版本和其他浏览器则不会

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/web-chat#15]

**Comment by imndx** [comment]
你好，能否提供一些日志，这个问题测试比较麻烦。

**Comment by Charlie191011** [comment]
<img width="1436" alt="微信图片_20200724113810" src="https://user-images.githubusercontent.com/61824879/88358650-615b7080-cda2-11ea-9c8b-51303ff73da1.png">
[Console.txt](https://github.com/wildfirechat/web-chat/files/4970098/Console.txt)
<img width="1428" alt="微信图片_20200724113802" src="https://user-images.githubusercontent.com/61824879/88358651-64566100-cda2-11ea-8fb0-1ed2dbed5a9d.png">
<img width="283" alt="微信图片_20200724113828" src="https://user-images.githubusercontent.com/61824879/88358653-64eef780-cda2-11ea-8927-5bae2498acb8.png">

**Comment by Charlie191011** [comment]
hi，please find:
<img width="283" alt="微信图片_20200724113828" src="https://user-images.githubusercontent.com/61824879/88358677-82bc5c80-cda2-11ea-8fcb-e9a521299779.png">
<img width="1436" alt="微信图片_20200724113810" src="https://user-images.githubusercontent.com/61824879/88358679-851eb680-cda2-11ea-9532-58aad215ffc8.png">
<img width="1428" alt="微信图片_20200724113802" src="https://user-images.githubusercontent.com/61824879/88358695-8f40b500-cda2-11ea-90e2-985d2a85fa03.png">
[Console.txt](https://github.com/wildfirechat/web-chat/files/4970101/Console.txt)

**Comment by imndx** [comment]
你好，这个问题是因为im server版本太旧了，请升级到最新。
