### ISSUE TITLE
Safari浏览器登录进去以后，可能会存在会话列表抖动等不稳定情况，怀疑是route方法多次请求导致

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/web-chat#16]

**Comment by imndx** [comment]
Safari 不支持 ```Access-Control-Allow-Methods: * ```，请确保 IM Server之前的 LB，不会将 http ```OPTIONS```对路径 ```/route```的请求中的header改写，正确值如下：

```Access-Control-Allow-Methods: p,uid,cid,appId,appKey,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma```
