### ISSUE TITLE
请增加删除消息功能【非本地删除】

### ISSUE THREAD

**Issue by FourLeafClover** [wildfirechat/web-chat#21]
期望SDK提供新的方法支持单聊和群聊删除消息(该消息可以是自己发送的也可以是别人发送)

删除消息的人的所有终端都看不到删除后的消息，单聊对方 和 群聊天中的其他人 还是能查看到该消息 。

**Comment by heavyrain2012** [comment]
这个功能由于我们数据存储方式问题，无法在服务器端完美支持。如果需要这个功能，请在客户端二次开发，可以删除消息时发送一个不可见消息，包含删除的消息id，其它端收到后，删掉对应消息。如果是web或者小程序端，需要根据这个消息记录下来已删除消息的id，然后在拉取远端消息时过滤掉
