### ISSUE TITLE
自定义群conversation.line,进入群后无法获取加群之前的历史消息

### ISSUE THREAD

**Issue by FourLeafClover** [wildfirechat/web-chat#24]
场景
1. 服务端开启了获取历史消息配置
2. 群会话自定义line。发现用户加群后，无法获取加群之前的消息
期望
能获取到加群之前的所有群消息

**Comment by imndx** [comment]
你好，Android、iOS有这个问题吗？

**Comment by FourLeafClover** [comment]
@imndx  没试过，目前自定义line只有web端才有这功能。

**Comment by FourLeafClover** [comment]
@imndx 刚测试过了和line没关系。   目前群聊是我把A踢出去群后再把A拉入群。 A登录IM后无法获取被踢出群这个时间段的消息。可以实现获取被踢出群时间段的消息的功能吗？ 比如在创建群的时候去设置该群是否支持获取所有聊天记录。

**Comment by heavyrain2012** [comment]
这个难度比较大，我们正在进行分析
