### ISSUE TITLE
proto.min.js文件报错：Uncaught Error: illegal buffer——现象：不能正常的接收信息

### ISSUE THREAD

**Issue by Potato-X** [wildfirechat/web-chat#26]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

### Web SDK 版本信息
可通过调用```wfc.getVersion```或在```proto.min.js```里面搜索```WFCWebSDKVersion-```获取。

### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

### 日志
请附上相关的错误

### 预期结果
你认为正确的表现应该是什么样的。

### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。

### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
你好，请提供一下控制台下的全部日志。

**Comment by imndx** [comment]
no response.
