### ISSUE TITLE
mac 报错 

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/web-chat#3]
> ref@1.3.5 install /Users/dotcool/Documents/project/web-chat/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:222:30: error: no matching member function for call to 'BooleanValue'
  bool persistent = info[3]->BooleanValue();
                    ~~~~~~~~~^~~~~~~~~~~~
/Users/dotcool/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2603:8: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/dotcool/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2606:51: note: candidate function not viable: requires single argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/binding.cc:253:38: error: too few arguments to function call, single argument 'context' was not specified
  size_t size = info[2]->Uint32Value();
                ~~~~~~~~~~~~~~~~~~~~ ^
/Users

**Comment by imndx** [comment]
确定这个报错是```web-chat```项目的报错吗？

**Comment by dotcool** [comment]
确定哦

**Comment by imndx** [comment]
你node版本是多少？
我的node版本是```v10.16.3```，一起正常

**Comment by dotcool** [comment]
我之前的版本是v12.12.0 换成你的版本确实没有报编译错误了。但是扫码之后还是没法正确跳转到会话列表页面哦

提示这个错误

clientId d5f82ad5-e977-4d6b-afbe-ef8eed93b26b
proto.min.js?ccb9:1 route error 1

**Comment by imndx** [comment]
web-chat依赖于web sdk，web sdk是付费的，请参考[费用](http://docs.wildfirechat.cn/#/费用)
