### ISSUE TITLE
加入聊天室不会拉取消息

### ISSUE THREAD

**Issue by q32757468** [wildfirechat/web-chat#30]
### Web SDK 版本信息
WFCWebSDKVersion-2020-09-09

### 操作说明
调用joinChatroom方法，走了成功的回调

### 表现现象
没有自动拉取聊天室中的历史消息

### 日志
![image](https://user-images.githubusercontent.com/43193877/93073128-06187100-f6b5-11ea-8f65-6472706b3f64.png)
![image](https://user-images.githubusercontent.com/43193877/93073145-0ca6e880-f6b5-11ea-9555-6eef70c655ee.png)

### 预期结果
应该会自动拉取部分消息，之前七月份某版本是正常的

### 补充条件
必然出现

**Comment by imndx** [comment]
你好，根据上面的```pull chatroom message result xxx``` 日志显示，成功拉取到了6条消息
