### ISSUE TITLE
获取聊天室信息失败

### ISSUE THREAD

**Issue by q32757468** [wildfirechat/web-chat#31]
### Web SDK 版本信息
WFCWebSDKVersion-2020-09-09

### 操作说明
调用getChatroomInfo方法，第二个参数传入 new Date().getTime()

### 表现现象
走了失败的回调，code为0

### 日志
![image](https://user-images.githubusercontent.com/43193877/93074187-960aea80-f6b6-11ea-8783-a9f9a87f2a38.png)

### 补充条件
必出现

**Comment by imndx** [comment]
你好，```getChatroomInfo```第二个参数```updateDt```表示拉取这个时间点之后的更新，需要服务端的```chatRoomInfo#updateDt```比传入的大，才会拉取。

如果本地没有对应的```chatRoomInfo```，请传0

**Comment by q32757468** [comment]
> 你好，`getChatroomInfo`第二个参数`updateDt`表示拉取这个时间点之后的更新，需要服务端的`chatRoomInfo#updateDt`比传入的大，才会拉取。
> 
> 如果本地没有对应的`chatRoomInfo`，请传0

时间传0之后会走成功的回调了，但是结果不正确
![image](https://user-images.githubusercontent.com/43193877/93152831-4c5fe580-f732-11ea-963e-abb2011e6f46.png)
