### ISSUE TITLE
撤回功能

### ISSUE THREAD

**Issue by FourLeafClover** [wildfirechat/web-chat#34]
**问题** 
同一个账号登录APP和Web端，APP端撤回消息后,Web端的reacallMesage.content.extra里面c字段为空。Web主动撤回消息，web端和app端的recallMessage.content.extra中c字段包含了之前的消息内容。
**期望**
期望APP端撤回消息后，web端收到的extra.c字段包含之前的消息内容

**Comment by imndx** [comment]
已修复，请先测试一下demo

**Comment by FourLeafClover** [comment]
@imndx 还是不行extra.c字段依旧是空字符串
