### ISSUE TITLE
下载仓库代码后无法在本地运行会propt.min.js里代码有报错； release版本打包后是electron包不是web包

### ISSUE THREAD

**Issue by jockw** [wildfirechat/web-chat#35]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

### Web SDK 版本信息
可通过调用```wfc.getVersion```或在```proto.min.js```里面搜索```WFCWebSDKVersion-```获取。

### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

### 日志
请附上相关的错误

### 预期结果
你认为正确的表现应该是什么样的。

### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。

### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
请贴出错误信息

**Comment by jockw** [comment]
![image](https://user-images.githubusercontent.com/29272661/97840250-a8042380-1d1e-11eb-8235-9f7b480cd77b.png)
![image](https://user-images.githubusercontent.com/29272661/97840340-c538f200-1d1e-11eb-9dc2-b337857c98a9.png)

**Comment by imndx** [comment]
你好，web sdk需要付费才可以使用，可以先申请[试用](https://docs.wildfirechat.cn/trial/)
