### ISSUE TITLE
web-chat 在platform.js中强制关联了react的相关Menu内容和Trigger，不利于对其他语言的支持。建议提供的基础API需要与具体的某个应用脱勾，方便支持Vue等其他语言

### ISSUE THREAD

**Issue by jiangzhu1212** [wildfirechat/web-chat#36]
web-chat 在platform.js中强制关联了react的相关Menu内容和Trigger，不利于对其他语言的支持。建议提供的基础API需要与具体的某个应用脱勾，方便支持Vue等其他语言

**Comment by imndx** [comment]
已解决，请参考 f999c31c9fafad69b91d295ce1721742c5756676
