### ISSUE TITLE
h5 im运行不了

### ISSUE THREAD

**Issue by panwent** [wildfirechat/web-chat#4]
G:\工作内容\客户、个人及公司资料存放\野火im\web-chat\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\zm\AppData\Roa
ming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: E:\python.EXE -c import platform; print(platform.python_version());
gyp ERR! stack ImportError: No module named site
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:12)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\Node\\node.exe" "C:\\Users\\zm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\工作内容\客户、个人及公司资料存放\野火im\web-chat\node_modules\ref
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> ffi@2.3.0 install G:\工作内容\客户、个人及公司资料存放\野火im\web-chat\node_modules\ffi
> node-gyp rebuild

G:\工作内容\客户、个人及公司资料存放\野火im\web-chat\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Users\zm\AppData\Roa
ming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: E:\python.EXE -c import platform; print(platform.python_version());
gyp ERR! stack ImportError: No module named site
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:12)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\Node\\node.exe" "C:\\Users\\zm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\工作内容\客户、个人及公司资料存放\野火im\web-chat\node_modules\ffi
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zm\AppData\Roaming\npm-cache\_logs\2020-01-10T05_38_27_935Z-debug.log

上面是报错信息

**Comment by imndx** [comment]
请更新代码测试
