### ISSUE TITLE
【web sdk】wfc.clearConversationUnreadStatus 某些情况下不生效

### ISSUE THREAD

**Issue by Frank-C-Zhang** [wildfirechat/web-chat#40]
A给B发送消息，B未读，B删除和A的会话。然后B调用setConversationTimestamp重新创建该会话,创建会话后执行了clearConversationUnreadStatus 但是 A显示的之前的消息还是未读。 A 发送一条消息给B。 B再执行clearConversationUnreadStatus 消息才会变成已读。。。 群聊也有这个问题。

**Comment by heavyrain2012** [comment]
未读的处理流程是，A调用clearConversationUnreadStatus时，检查会话中的最大消息的时间，然后把这个时间告诉B，B就知道A读到这个时间了。如果A删除了会话和消息，当调用clearConversationUnreadStatus时，A就找不到最后一条消息的时间，所以就没有办法通知B他读到那个时间点了。

这个问题出现的概率比较小，且影响也不大，如果修改的话也比较复杂，还是保持问题现状吧
