### ISSUE TITLE
[react-demo] callEndReson推送不对

### ISSUE THREAD

**Issue by Frank-C-Zhang** [wildfirechat/web-chat#41]
Web端 A给B发送语音。 B拒绝邀请主动挂断。
A的sessionCallback.didCallEndWithReason接收到的reson不对，
预期 REASON_RemoteHangup， 实际 RemoteNetworkError.

麻烦也检查一下其他场景推送。

**Comment by imndx** [comment]
已修复，请更新到最新代码。
