### ISSUE TITLE
请问proto.min.js未压缩代码如何获取？

### ISSUE THREAD

**Issue by yaphone** [wildfirechat/web-chat#6]
由于项目需要修改proto.mini.js的一些内容，请问如何获取未压缩的源码，THX！

**Comment by imndx** [comment]
你好，这个文件不开源。需要购买授权才能修改。

**Comment by yaphone** [comment]
请问授权相关如何咨询？

**Comment by imndx** [comment]
@yaphone 这儿有详细的说明[docs](http://docs.wildfirechat.cn/)

另外，可以微信添加 wfchat 进行咨询
