### ISSUE TITLE
获取最后一条消息为空(有历史消息) lastMessage

### ISSUE THREAD

**Issue by eyea** [wildfirechat/web-chat#7]
刷新列表时候 会话的 lastMessage  为空，其实有历史的聊天记录的。
收发消息正常。

**Comment by imndx** [comment]
你好，请确认一下：

获取历史消息时，传入的conversation对象，里面应包含：```conversationType```字段。可通过new Conversation(type, line, target)构造，或者```{conversationType:0, line:0, target:'xxx'}

下个版本中，我们将做兼容处理。
